name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository first
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Change to the project directory (AFTER checkout)
      - name: Change Directory
        run: cd bolt.new && ls -la

      # Get commit SHA
      - name: Extract Commit SHA
        run: echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      # Login to Docker Hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      # Login to AWS ECR
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_REGISTRY }}

      # Build Docker Image with Commit SHA as tag
      - name: Build Docker Image
        run: docker build -t dhruvwebdev146/deploify:${{ env.COMMIT_SHA }} .

      # Tag and Push to Docker Hub
      - name: Tag and Push to Docker Hub
        run: |
          docker tag dhruvwebdev146/deploify:${{ env.COMMIT_SHA }} dhruvwebdev146/deploify:latest
          docker push dhruvwebdev146/deploify:${{ env.COMMIT_SHA }}
          docker push dhruvwebdev146/deploify:latest  # Update latest tag

      # Tag and Push to AWS ECR
      - name: Tag and Push to AWS ECR
        run: |
          docker tag dhruvwebdev146/deploify:${{ env.COMMIT_SHA }} ${{ secrets.AWS_ECR_REGISTRY }}:${{ env.COMMIT_SHA }}
          docker tag dhruvwebdev146/deploify:${{ env.COMMIT_SHA }} ${{ secrets.AWS_ECR_REGISTRY }}
          docker push ${{ secrets.AWS_ECR_REGISTRY }}:${{ env.COMMIT_SHA }}
          docker push ${{ secrets.AWS_ECR_REGISTRY }}
