name: Demo Test Action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Create Neon Branch
        id: create_neon_branch_encode
        uses: neondatabase/create-branch-action@v5
        with:
          project_id: ${{ vars.NEON_PROJECT_ID }}
          branch_name: preview/pr-${{ github.event.number }}-${{ github.sha }}
          api_key: ${{ secrets.NEON_API_KEY }}

      - name: Install dependencies in bolt.new
        run: |
          cd bolt.new
          npm install --force

      - name: Run tests in bolt.new
        run: |
          cd bolt.new
          npm test

      - name: Test DB Connection and Requests
        run: |
          cd bolt.new
          node -e "
            const { Client } = require('pg');
            const client = new Client({
              connectionString: '${{ steps.create_neon_branch_encode.outputs.db_url }}',
            });
            client.connect()
              .then(() => {
                console.log('DB connection successful');
                return client.query('SELECT 1');
              })
              .then(res => {
                console.log('DB Test Query Result:', res.rows);
                client.end();
              })
              .catch(err => {
                console.error('DB connection error:', err.stack);
                process.exit(1);
              });
          "
