name: Demo Test Action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Change directory to bolt.new
        run: cd bolt.new

      - name: Install dependencies in bolt.new
        run: |
          cd bolt.new
          npm install --force

      - name: Run tests in bolt.new
        run: |
          cd bolt.new
          npm test
