name: Demo Test Action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Create Neon Branch
        id: create_neon_branch_encode
        uses: neondatabase/create-branch-action@v5
        with:
          project_id: ${{ vars.NEON_PROJECT_ID }}
          branch_name: preview/pr-${{ github.event.number }}-${{ github.sha }}
          api_key: ${{ secrets.NEON_API_KEY }}

      - name: Install dependencies in bolt.new
        run: |
          cd bolt.new
          npm install --force

      - name: Set up DATABASE_URL for Prisma
        run: |
          echo "DATABASE_URL=${{ steps.create_neon_branch_encode.outputs.db_url }}" >> bolt.new/.env

      - name: Run Prisma Migrations (if needed)
        run: |
          cd bolt.new
          npx prisma migrate deploy

      - name: Run tests in bolt.new
        run: |
          cd bolt.new
          npm test
